### ISSUE TITLE
logData() not working after initial call

### ISSUE THREAD

**Issue by KravitzLab** [KravitzLabDevices/FED4#2]
logData() works in the begin function, creating a new file with Event=Startup.  
Subsequent calls to logData() in the script cause it to time out and not write to the file.  Added debugging code to the logData() function, confirming that it fails to open the file after the first call.

Also confirmed on the Serial Output that the SD card successfully reinitializes after wakeup:
![image](https://github.com/user-attachments/assets/2371a4f5-f5a8-4fd8-a894-4d8f6a83c4de)

**Comment by mattgaidica** [comment]
Do you get any of these print statements at logData? @KravitzLab 

void FED4::logData()
{
    greenPix();
    
    Serial.println ("Getting time");
    DateTime now = rtc.now();
    
    Serial.print ("Attempting to open file: ");
    Serial.print (filename);
    File dataFile = SD.open(filename, FILE_WRITE);

    if (dataFile)
    {
    Serial.println (" ... opened");
        // DateTime, Event
        dataFile.printf("%04d-%02d-%02d %02d:%02d:%02d,%s,",
                        now.year(), now.month(), now.day(),
                        now.hour(), now.minute(), now.second(),
                        event.c_str());

        // Counters
        dataFile.printf("%d,%d,%d,%d,%d,",
                        pelletCount, leftCount, rightCount, centerCount, wakeCount);

        // Battery and Environmental
        dataFile.printf("%.2f,%.1f,",
                        getBatteryVoltage(),
                        getTemperature());

        // Memory stats
        dataFile.printf("%d,%d,%d\n",
                        ESP.getFreeHeap(),
                        ESP.getHeapSize(),
                        ESP.getMinFreeHeap());

        dataFile.close();
    }
    
    else {
    Serial.println(" ... Warning: SD file not opened.");
    }
    noPix();
}

**Comment by mattgaidica** [comment]
filenames need to be prepended by '/' in ESP32, pushed update

**Comment by KravitzLab** [comment]
Reopening this as we're still getting "Warning: SD file not opened."  We've tried the following two approaches but neither works.  I can try more on this over the weekend, it's annoying!

Approach 1:
File dataFile = SD.open(String("/") + filename, FILE_WRITE);

Approach 2: 
char fullPath[22];
snprintf(fullPath, sizeof(fullPath), "/%s", filename);
File dataFile = SD.open(fullPath, FILE_WRITE);

Also not sure why this works in the createLogFile function?
![image](https://github.com/user-attachments/assets/b97d385e-aa37-4232-bb1f-cd03141c197d)

**Comment by mattgaidica** [comment]
Fixed once in software, now fixed in hardware (3.3V tie)
