### ISSUE TITLE
make "event" an argument of logdata()

### ISSUE THREAD

**Issue by KravitzLab** [KravitzLabDevices/FED4#5]
Current useage is:        
setEvent("PelletDrop");
logData();

Make event an argument for LogData:
logData(event="Pellet");

**Comment by mattgaidica** [comment]
Added as optional arg

**Comment by mattgaidica** [comment]
CLose

**Comment by KravitzLab** [comment]
NeuroTech Hub Premium: 
"All issues will be resolved within 15 minutes!"
